FROM debian8

MAINTAINER 坚硬的石头 do_nb@outlook.com

RUN apt-get update && apt-get install -y git-flow ctags\
        vim-conque vim vim-common vim-doc vim-lesstif vim-nox \
        vim-runtime vim-tiny vim-addon-manager vim-addon-mw-utils \
        vim-ctrlp vim-fugitive vim-pathogen vim-scripts vim-snipmate \
        vim-snippets vim-syntastic vim-tabular vim-tlib vim-ultisnips \
        vim-vimoutliner && \
        rm -rf /var/lib/apt/lists/*

